"use client";

import Image from "next/image";
import Link from "next/link";
import { BookOpen, ChevronLeft, ChevronRight, CirclePlus, Pencil, RefreshCw, Search } from "lucide-react";
import { useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useCategories } from "@/hooks/use-categories";
import { useBooks } from "@/hooks/use-books";
import type { AdminBookFilters, BookAccessType, BookListItem, BookStatus } from "@/types/book";

const pageSize = 10;
export function BookManagement() {
  const [filters, setFilters] = useState<AdminBookFilters>({ page: 0, size: pageSize });
  const booksQuery = useBooks(filters);
  const categoriesQuery = useCategories();
  const data = booksQuery.data;
  const updateFilter = (changes: Partial<AdminBookFilters>) => setFilters((current) => ({ ...current, ...changes, page: changes.page ?? 0 }));
  return <div className="space-y-readora-lg"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-muted-foreground">Manage all titles in your Readora library.</p><h1 className="mt-1 font-heading text-3xl font-semibold">Books</h1></div><Button render={<Link href="/admin/books/new" />}><CirclePlus />Add book</Button></div><BookFilters categories={categoriesQuery.data ?? []} filters={filters} onChange={updateFilter} />{booksQuery.isLoading ? <BookTableSkeleton /> : null}{booksQuery.isError ? <EmptyState title="Couldn’t load books" description="Please check the connection and try again." action={<Button onClick={() => void booksQuery.refetch()} type="button"><RefreshCw />Retry</Button>} /> : null}{!booksQuery.isLoading && !booksQuery.isError && data && data.content.length === 0 ? <EmptyState title="No books found" description="Try different filters or add the first title to the library." action={<Button render={<Link href="/admin/books/new" />}><CirclePlus />Add book</Button>} /> : null}{data?.content.length ? <><BookTable books={data.content} /><div className="flex items-center justify-between text-sm text-muted-foreground"><span>Showing {data.content.length} of {data.totalElements} books</span><div className="flex gap-2"><Button disabled={data.page === 0} onClick={() => updateFilter({ page: data.page - 1 })} size="sm" type="button" variant="outline"><ChevronLeft />Previous</Button><span className="px-2 py-1">Page {data.page + 1} of {Math.max(data.totalPages, 1)}</span><Button disabled={data.last} onClick={() => updateFilter({ page: data.page + 1 })} size="sm" type="button" variant="outline">Next<ChevronRight /></Button></div></div></> : null}</div>;
}
function BookFilters({ categories, filters, onChange }: { categories: { id: number; name: string }[]; filters: AdminBookFilters; onChange: (changes: Partial<AdminBookFilters>) => void }) { return <Card className="border border-border py-0 shadow-card"><CardContent className="grid gap-3 p-readora-md md:grid-cols-4"><div className="relative md:col-span-2"><Search className="pointer-events-none absolute top-2 left-2.5 size-4 text-muted-foreground" /><Input className="pl-8" onChange={(event) => onChange({ search: event.target.value || undefined })} placeholder="Search title or author…" value={filters.search ?? ""} /></div><select className="h-8 rounded-lg border border-input bg-transparent px-2.5 text-sm" onChange={(event) => onChange({ status: (event.target.value || undefined) as BookStatus | undefined })} value={filters.status ?? ""}><option value="">All statuses</option><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select><select className="h-8 rounded-lg border border-input bg-transparent px-2.5 text-sm" onChange={(event) => onChange({ accessType: (event.target.value || undefined) as BookAccessType | undefined })} value={filters.accessType ?? ""}><option value="">All access</option><option value="FREE">Free</option><option value="PREMIUM">Premium</option></select><select className="h-8 rounded-lg border border-input bg-transparent px-2.5 text-sm md:col-span-2" onChange={(event) => onChange({ categoryId: event.target.value ? Number(event.target.value) : undefined })} value={filters.categoryId ?? ""}><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><Button onClick={() => onChange({ search: undefined, status: undefined, accessType: undefined, categoryId: undefined })} type="button" variant="outline">Clear filters</Button></CardContent></Card>; }
function BookTable({ books }: { books: BookListItem[] }) { return <Card className="border border-border py-0 shadow-card"><CardContent className="p-0"><Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead className="px-4">Book</TableHead><TableHead>Access</TableHead><TableHead>Status</TableHead><TableHead>Categories</TableHead><TableHead>Created</TableHead><TableHead className="px-4 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{books.map((book) => <TableRow key={book.id}><TableCell className="px-4"><div className="flex items-center gap-3"><BookCover book={book} /><div className="min-w-0"><p className="max-w-52 truncate font-medium">{book.title}</p><p className="text-xs text-muted-foreground">{book.author}</p></div></div></TableCell><TableCell><Badge className={book.accessType === "PREMIUM" ? "bg-premium text-primary-foreground" : "bg-success/10 text-success"} variant="secondary">{book.accessType}</Badge></TableCell><TableCell><Badge variant="outline">{book.status ?? "—"}</Badge></TableCell><TableCell className="max-w-48 whitespace-normal text-xs text-muted-foreground">{book.categories.map((category) => category.name).join(", ") || "—"}</TableCell><TableCell className="text-muted-foreground">{new Date(book.createdAt).toLocaleDateString()}</TableCell><TableCell className="px-4 text-right"><Button aria-label={`Edit ${book.title}`} render={<Link href={`/admin/books/${book.id}/edit`} />} size="icon-sm" variant="ghost"><Pencil /></Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>; }
function BookCover({ book }: { book: BookListItem }) { if (!book.coverUrl) return <span className="flex h-12 w-9 items-center justify-center rounded-md bg-secondary text-primary"><BookOpen className="size-4" /></span>; return <span className="relative h-12 w-9 overflow-hidden rounded-md bg-secondary"><Image alt={`Cover of ${book.title}`} className="object-cover" fill sizes="36px" src={book.coverUrl} /></span>; }
function BookTableSkeleton() { return <Card className="border border-border py-0 shadow-card"><CardContent className="space-y-4 p-readora-md">{[0,1,2,3,4].map((item) => <Skeleton className="h-12 w-full" key={item} />)}</CardContent></Card>; }
